"""description of changes

Revision ID: f5cee76147a4
Revises: a64c4524e3da
Create Date: 2025-10-23 15:49:54.516501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cee76147a4'
down_revision: Union[str, Sequence[str], None] = 'a64c4524e3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direction_food_id'), 'direction', ['food_id'], unique=False)
    op.create_index(op.f('ix_direction_id'), 'direction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direction_id'), table_name='direction')
    op.drop_index(op.f('ix_direction_food_id'), table_name='direction')
    op.drop_table('direction')
    # ### end Alembic commands ###
