vlm:
  default_provider: openrouter
  providers:
    openrouter:
      model: mistralai/mistral-small-3.2-24b-instruct:free
      rate_limit:
        requests_per_minute: 20
        requests_per_day: 1000
      timeout: 30
      retry:
        max_attempts: 3
        backoff_factor: 2

    gemini:
      model: gemini-2.0-flash-exp
      rate_limit:
        requests_per_minute: 15
        requests_per_day: unlimited
      timeout: 30

llm:
  default_provider: gemini
  providers:
    gemini:
      model: gemini-2.5-flash
      cost_per_1k_tokens: 0.0  # Free tier
      rate_limit:
        requests_per_minute: 15

    openrouter:
      model: mistralai/mistral-small-3.2-24b-instruct:free
      cost_per_1k_tokens: 0.0
      rate_limit:
        requests_per_minute: 20

# Feature flags
features:
  enable_streaming: true
  enable_cost_tracking: true
  enable_fallback: true

# Monitoring
monitoring:
  log_requests: true
  track_latency: true
  alert_on_errors: true
